name: docs deploy
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'released' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: make deploy-docs
