---
name: On Push and Pull Requests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  Check:
    name: Check and Lint
    uses: ./.github/workflows/mypy.yml

  Test:
    name: Test
    needs:
      - Check
    if: needs.Check.result == 'success'
    uses: ./.github/workflows/tests.yml
    secrets:
      GOOGLE_CLIENT_KEY: ${{ secrets.GOOGLE_CLIENT_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
