---
name: On Release

on:
  release:
    types:
      - released

jobs:
  Check:
    name: Check and Lint
    uses: ./.github/workflows/mypy.yml

  Test:
    name: Test
    needs:
      - Check
    if: needs.Check.result == 'success'
    uses: ./.github/workflows/tests.yml

  Release_Check:
    name: Check Release
    needs:
      - Test
    if: needs.Test.result == 'success'
    uses: ./.github/workflows/release_check.yml

  Release:
    name: Release
    needs:
      - Release_Check
    if: needs.Release_Check.result == 'success'
    uses: ./.github/workflows/release_steps.yml


  Docs:
    name: Deploy Docs
    needs:
      - Release
    if: needs.Release.result == 'success'
    uses: ./.github/workflows/gh-pages.yml